name: dqed1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bottom_sheet: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  path: ^1.8.3
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  whatsapp_stickers_plus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Documan
      fonts:
        - asset: assets/Documan/DocumanBold.otf
        - asset: assets/Documan/DocumanExtraLight.otf
        - asset: assets/Documan/DocumanHeavy.otf
        - asset: assets/Documan/DocumanLazer.otf
        - asset: assets/Documan/DocumanLight.otf
        - asset: assets/Documan/DocumanMedium.otf
        - asset: assets/Documan/DocumanRegular.otf
        - asset: assets/Documan/DocumanSemiBold.otf
        - asset: assets/Documan/DocumanThin.otf
